version: "3.7"

services:
  proxy:
    image: traefik
    container_name: traefik_proxy
    ports: 
      - "80:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yml:/traefik.yml
      - ./log/traefik.log:/traefik.log
      - ./certs:/etc/certs:ro

  nginx:
    image: nginx
    container_name: nginx
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`nginx.app.test`)"
      - "traefik.http.routers.nginx.tls=true"

  app:
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    container_name: app
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`apache.app.test`)"
      - "traefik.http.routers.app.tls=true"