version: "3.7"

services: 
  proxy:
    image: traefik
    ports: 
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/traefik.yml

  nginx:
    image: nginx
    labels: 
      - "traefik.http.routers.nginx.rule=Host(`nginx.app.test`)"