version: "3.7"

services:
  proxy:
    image: traefik
    container_name: traefik_proxy
    ports: 
      - "80:80"
      - "8080:8080"
      - "443:443" 
    networks:
      - traefik_proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yml:/traefik.yml
      - ./log/traefik.log:/traefik.log
      - ./certs:/etc/certs:ro
      
networks:
  traefik_proxy:
    external: true