api:
  insecure: true

# Remover command docker-compose.yml line 6
#     command: --providers.docker
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    # Ocultar service
    # Para exibir in labels - "traefik.enable=true"
    exposedByDefault: false

# Writing Logs to a File, in JSON
log:
  filePath: "/traefik.log"
  level: INFO
#  format: json