version: "3.7"

services:
  nginx:
    image: nginx
    container_name: nginx
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`nginx.app.test`)"
      - "traefik.http.routers.nginx.tls=true"
    networks:
      - traefik_proxy

networks:
  traefik_proxy:
    external: true